# Generated by Django 6.0.2 on 2026-02-15 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('injection', 'Injection Attacks'), ('xss', 'XSS'), ('best_practices', 'Best Practices'), ('api_security', 'API Security'), ('authentication', 'Authentication'), ('security_headers', 'Security Headers'), ('access_control', 'Access Control'), ('cryptography', 'Cryptography'), ('network_security', 'Network Security')], max_length=50)),
                ('author', models.CharField(default='Security Team', max_length=100)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('image', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
