# Generated by Django 5.2.11 on 2026-03-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_learning_taxonomy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='learn_artic_slug_db738b_idx',
            old_name='learn_artic_slug_65cace_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='learn_artic_is_publ_a9e007_idx',
            old_name='learn_artic_is_publ_ef6ea9_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='learn_artic_status_6788c8_idx',
            old_name='learn_artic_status_67860c_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='learn_artic_difficu_d50ff0_idx',
            old_name='learn_artic_difficu_adba1a_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='learn_categ_slug_c8c029_idx',
            old_name='learn_categ_slug_8894bb_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='learn_categ_is_acti_3a33e1_idx',
            old_name='learn_categ_is_acti_10b6f9_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='learn_categ_parent__7e2007_idx',
            old_name='learn_categ_parent__d05499_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='learn_tag_slug_ff78bb_idx',
            old_name='learn_tag_slug_7d91ea_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='learn_tag_tag_typ_9f18a7_idx',
            old_name='learn_tag_tag_typ_98f9ad_idx',
        ),
    ]
