# Generated by Django 4.2.30 on 2026-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_plan_organization_aiconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI Platform'), ('anthropic', 'Anthropic Console'), ('gemini', 'Google AI Studio (Gemini)'), ('groq', 'Groq Cloud'), ('openrouter', 'OpenRouter'), ('cerebras', 'Cerebras Cloud'), ('mistral', 'Mistral AI La Plateforme'), ('together', 'Together AI'), ('fireworks', 'Fireworks AI'), ('xai', 'xAI API'), ('custom', 'Custom Provider')], default='openai', max_length=50),
        ),
    ]
