# Generated by Django 6.0.2 on 2026-02-15 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('website', 'Website'), ('file', 'File'), ('url', 'URL')], max_length=20)),
                ('target', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('depth', models.CharField(choices=[('shallow', 'Shallow'), ('medium', 'Medium'), ('deep', 'Deep')], default='medium', max_length=20)),
                ('include_subdomains', models.BooleanField(default=False)),
                ('check_ssl', models.BooleanField(default=True)),
                ('follow_redirects', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='scan_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('csv', 'CSV'), ('xml', 'XML'), ('html', 'HTML')], max_length=10)),
                ('file', models.FileField(upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanning.scan')),
            ],
            options={
                'db_table': 'scan_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('remediation', models.TextField()),
                ('cwe', models.CharField(blank=True, default='', max_length=20)),
                ('cvss', models.FloatField(default=0.0)),
                ('affected_url', models.URLField(blank=True, default='', max_length=2048)),
                ('evidence', models.TextField(blank=True, default='')),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanning.scan')),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
                'db_table': 'vulnerabilities',
                'ordering': ['-cvss', 'severity'],
            },
        ),
    ]
