# Generated by Django 5.2.11 on 2026-03-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_scan_recon_data_alter_vulnerability_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_phase',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scan',
            name='pages_crawled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='attack_chain',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='false_positive_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
