# Generated by Django 5.2.11 on 2026-03-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0003_scan_current_phase_scan_pages_crawled_scan_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('continuous', 'Continuous'), ('hunting', 'Hunting')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='next_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='parent_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_scans', to='scanning.scan'),
        ),
    ]
