# Generated by Django 5.2.11 on 2026-03-07 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0006_phase44_api_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='oob_callback',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_type', models.CharField(choices=[('form', 'Form Login'), ('api', 'API Token'), ('cookie', 'Cookie'), ('bearer', 'Bearer Token'), ('custom', 'Custom Header')], max_length=20)),
                ('config_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_configs', to='scanning.scan')),
            ],
            options={
                'db_table': 'auth_configs',
            },
        ),
    ]
