# Generated by Django 5.2.11 on 2026-03-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0011_vulnerability_tool_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='discovered_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='scope_type',
            field=models.CharField(choices=[('single_domain', 'Single Domain'), ('wildcard', 'Wildcard Domain'), ('wide_scope', 'Wide Scope')], default='single_domain', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='seed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scan',
            name='include_subdomains',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('website', 'Website')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
