# Generated by Django 5.2.11 on 2026-03-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0012_scope_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_tool',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='scan',
            name='phase_timings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
