# Generated by Django 5.2.11 on 2026-03-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0013_live_scan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='data_version',
            field=models.IntegerField(default=0),
        ),
    ]
