# Generated by Django 5.2.11 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0014_data_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='control_external_tools',
            field=models.BooleanField(default=True),
        ),
    ]
