# Generated by Django 6.0.6 on 2026-06-23 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_plan_organization_aiconfiguration_and_more'),
        ('scanning', '0015_scan_control_external_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='scan',
            name='selected_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ai_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ai_remediation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scan',
            name='depth',
            field=models.CharField(choices=[('shallow', 'Shallow'), ('medium', 'Medium'), ('deep', 'Deep'), ('custom', 'Custom')], default='medium', max_length=20),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_dns_verified', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_user_id', models.UUIDField(blank=True, null=True)),
                ('current_score', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='accounts.organization')),
            ],
            options={
                'db_table': 'targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='target_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanning.target'),
        ),
    ]
