# Generated by Django 6.0.6 on 2026-06-23 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0016_scan_organization_scan_selected_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password_hash', models.CharField(blank=True, default='', help_text='Optional password protection', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='scanning.scan')),
            ],
            options={
                'db_table': 'shared_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
