# Generated by Django 6.0.6 on 2026-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0017_sharedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='cost_meter_usd',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='scan',
            name='engagement_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='flow_status',
            field=models.CharField(default='initializing', max_length=50),
        ),
        migrations.AddField(
            model_name='scan',
            name='scope_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='task_graph',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='action_id_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='proof_capsule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='verification_status',
            field=models.CharField(choices=[('candidate', 'Candidate (Unverified)'), ('verified', 'Verified (3/3 Confirmed)'), ('unverified', 'Unverified (Replay Failed)')], default='candidate', max_length=20),
        ),
    ]
