# Generated by Django 6.0.2 on 2026-02-15 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('malware', 'Malware Detection'), ('phishing', 'Phishing Detection'), ('anomaly', 'Anomaly Detection')], max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_duration_seconds', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField(default=dict)),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ml.mlmodel')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='scanning.scan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
