# Generated by Django 5.2.11 on 2026-03-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='action_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
