# Generated by Django 5.2.11 on 2026-03-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_feedback_and_action_data_to_chatmessage'),
        ('scanning', '0014_data_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context_type',
            field=models.CharField(choices=[('general', 'General'), ('scan', 'Scan'), ('vulnerability', 'Vulnerability')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='scanning.scan'),
        ),
    ]
